//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About Us - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsHeadline")]
		public virtual string AboutUsHeadline => this.Value<string>(_publishedValueFallback, "aboutUsHeadline");

		///<summary>
		/// About Us - Img Alt Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsImgAltText")]
		public virtual string AboutUsImgAltText => this.Value<string>(_publishedValueFallback, "aboutUsImgAltText");

		///<summary>
		/// About Us - Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsQuote")]
		public virtual string AboutUsQuote => this.Value<string>(_publishedValueFallback, "aboutUsQuote");

		///<summary>
		/// About Us - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsSectionTitle")]
		public virtual string AboutUsSectionTitle => this.Value<string>(_publishedValueFallback, "aboutUsSectionTitle");

		///<summary>
		/// About Us - Signature Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsSignatureImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutUsSignatureImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutUsSignatureImg");

		///<summary>
		/// About Us - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText")]
		public virtual string AboutUsText => this.Value<string>(_publishedValueFallback, "aboutUsText");

		///<summary>
		/// Image Slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("imageSlider")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ImageSlider => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "imageSlider");

		///<summary>
		/// Our Projects - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourProjectsHeadline")]
		public virtual string OurProjectsHeadline => this.Value<string>(_publishedValueFallback, "ourProjectsHeadline");

		///<summary>
		/// Our Projects Image Slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourProjectsImageSlider")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel OurProjectsImageSlider => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "ourProjectsImageSlider");

		///<summary>
		/// Our Projects - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourProjectsSectionTitle")]
		public virtual string OurProjectsSectionTitle => this.Value<string>(_publishedValueFallback, "ourProjectsSectionTitle");

		///<summary>
		/// Our Services - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourServicesHeadline")]
		public virtual string OurServicesHeadline => this.Value<string>(_publishedValueFallback, "ourServicesHeadline");

		///<summary>
		/// Our Services - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourServicesSectionTitle")]
		public virtual string OurServicesSectionTitle => this.Value<string>(_publishedValueFallback, "ourServicesSectionTitle");

		///<summary>
		/// Page Logotype
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageLogotype")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops PageLogotype => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "pageLogotype");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Request Form Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("requestFormButtonText")]
		public virtual string RequestFormButtonText => this.Value<string>(_publishedValueFallback, "requestFormButtonText");

		///<summary>
		/// Request Form Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("requestFormText")]
		public virtual string RequestFormText => this.Value<string>(_publishedValueFallback, "requestFormText");

		///<summary>
		/// Request Form Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("requestFormTitle")]
		public virtual string RequestFormTitle => this.Value<string>(_publishedValueFallback, "requestFormTitle");

		///<summary>
		/// Showcase - Background Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseBackgroundImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ShowcaseBackgroundImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "showcaseBackgroundImg");

		///<summary>
		/// Showcase - Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseButtonText")]
		public virtual string ShowcaseButtonText => this.Value<string>(_publishedValueFallback, "showcaseButtonText");

		///<summary>
		/// Showcase - Button Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseButtonUrl")]
		public virtual string ShowcaseButtonUrl => this.Value<string>(_publishedValueFallback, "showcaseButtonUrl");

		///<summary>
		/// Showcase - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseHeadline")]
		public virtual string ShowcaseHeadline => this.Value<string>(_publishedValueFallback, "showcaseHeadline");

		///<summary>
		/// Showcase - Img Alt Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseImgAltText")]
		public virtual string ShowcaseImgAltText => this.Value<string>(_publishedValueFallback, "showcaseImgAltText");

		///<summary>
		/// Showcase - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showcaseText")]
		public virtual string ShowcaseText => this.Value<string>(_publishedValueFallback, "showcaseText");

		///<summary>
		/// Stories - Background Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesBackgroundImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops StoriesBackgroundImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "storiesBackgroundImg");

		///<summary>
		/// Stories - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesHeadline")]
		public virtual string StoriesHeadline => this.Value<string>(_publishedValueFallback, "storiesHeadline");

		///<summary>
		/// Stories - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesSectionTitle")]
		public virtual string StoriesSectionTitle => this.Value<string>(_publishedValueFallback, "storiesSectionTitle");

		///<summary>
		/// Stories - Selected Photo Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesSelectedPhotoImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops StoriesSelectedPhotoImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "storiesSelectedPhotoImg");

		///<summary>
		/// Stories - Statistic nr1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr1")]
		public virtual string StoriesStatisticNr1 => this.Value<string>(_publishedValueFallback, "storiesStatisticNr1");

		///<summary>
		/// Stories - Statistic nr1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr1Text")]
		public virtual string StoriesStatisticNr1Text => this.Value<string>(_publishedValueFallback, "storiesStatisticNr1Text");

		///<summary>
		/// Stories - Statistic nr2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr2")]
		public virtual string StoriesStatisticNr2 => this.Value<string>(_publishedValueFallback, "storiesStatisticNr2");

		///<summary>
		/// Stories - Statistic nr2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr2Text")]
		public virtual string StoriesStatisticNr2Text => this.Value<string>(_publishedValueFallback, "storiesStatisticNr2Text");

		///<summary>
		/// Stories - Statistic nr3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr3")]
		public virtual string StoriesStatisticNr3 => this.Value<string>(_publishedValueFallback, "storiesStatisticNr3");

		///<summary>
		/// Stories - Statistic nr3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storiesStatisticNr3Text")]
		public virtual string StoriesStatisticNr3Text => this.Value<string>(_publishedValueFallback, "storiesStatisticNr3Text");

		///<summary>
		/// Trusted By - Background Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByBackgroundImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TrustedByBackgroundImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "trustedByBackgroundImg");

		///<summary>
		/// Trusted By - Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByButtonText")]
		public virtual string TrustedByButtonText => this.Value<string>(_publishedValueFallback, "trustedByButtonText");

		///<summary>
		/// Trusted By - Button Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByButtonUrl")]
		public virtual string TrustedByButtonUrl => this.Value<string>(_publishedValueFallback, "trustedByButtonUrl");

		///<summary>
		/// Trusted By -  Img Alt Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByImgAltText")]
		public virtual string TrustedByImgAltText => this.Value<string>(_publishedValueFallback, "trustedByImgAltText");

		///<summary>
		/// Trusted By - Numbers In Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByNumbersInHeadline")]
		public virtual string TrustedByNumbersInHeadline => this.Value<string>(_publishedValueFallback, "trustedByNumbersInHeadline");

		///<summary>
		/// Trusted By - Section Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedBySectionHeadline")]
		public virtual string TrustedBySectionHeadline => this.Value<string>(_publishedValueFallback, "trustedBySectionHeadline");

		///<summary>
		/// Trusted By - Section Img
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedBySectionImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TrustedBySectionImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "trustedBySectionImg");

		///<summary>
		/// Trusted By - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustedByText")]
		public virtual string TrustedByText => this.Value<string>(_publishedValueFallback, "trustedByText");
	}
}
